#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

python /app/manage.py migrate --no-input
python /app/manage.py collectstatic --no-input

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app