services:
   api:
      build:
         context: .
         dockerfile: ./docker/local/django/Dockerfile
      command: /start
      volumes:
         - .:/app:z
         - static_volume:/app/staticfiles
         - media_volume:/app/mediafiles
      expose:
         - "8000"
      env_file:
         - ./.envs/.local/.django
         - ./.envs/.local/.postgres
      environment:
         - RUNNING_IN_DOCKER=true
      depends_on:
         - postgres
      networks:
         - arch-api

   postgres:
      build:
         context: .
         dockerfile: ./docker/local/postgres/Dockerfile
      volumes:
         - local_postgres_data:/var/lib/postgresql/data
         - ./backups:/backups
      ports:
         - "5433:5432"
      env_file:
         - ./.envs/.local/.postgres
      environment:
         - RUNNING_IN_DOCKER=true
      networks:
         - arch-api

   nginx:
      restart: always
      depends_on:
         - api
      volumes:
         - static_volume:/app/staticfiles
         - media_volume:/app/mediafiles
         - logs_store:/var/log/nginx
      build:
         context: .
         dockerfile: ./docker/local/nginx/Dockerfile
      ports:
         - "8080:80"
      networks:
         - arch-api

networks:
   arch-api:
      driver: bridge

volumes:
   static_volume:
   media_volume:
   local_postgres_data: {}
   logs_store:
