# Generated by Django 5.2.2 on 2025-06-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedworkbook",
            name="sheet_date",
            field=models.DateField(
                blank=True, help_text="Sunday date parsed from filename or sheet name"
            ),
        ),
    ]
