# Generated by Django 5.2.2 on 2025-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_alter_uploadedworkbook_sheet_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedworkbook",
            name="file_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
