# Generated by Django 5.2.2 on 2025-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_alter_uploadedworkbook_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedworkbook",
            name="sheet_date",
            field=models.DateField(
                help_text="Sunday date parsed from filename or sheet name", null=True
            ),
        ),
    ]
