# Generated by Django 5.2.2 on 2025-06-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analyzer", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sunday_date", models.DateField()),
                ("sunday_school", models.PositiveIntegerField(default=0)),
                ("adults", models.PositiveIntegerField(default=0)),
                (
                    "diff_abled",
                    models.PositiveIntegerField(default=0, verbose_name="diff_abled"),
                ),
                ("youth", models.PositiveIntegerField(default=0)),
                (
                    "total_collection",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("banked", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unbanked", models.DecimalField(decimal_places=2, max_digits=12)),
                ("remarks", models.TextField(blank=True)),
                (
                    "archdeaconry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="common.archdeaconry",
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="common.congregation",
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="common.parish",
                    ),
                ),
                (
                    "workbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="analyzer.uploadedworkbook",
                    ),
                ),
            ],
            options={
                "ordering": ["-sunday_date", "archdeaconry", "parish", "congregation"],
                "indexes": [
                    models.Index(
                        fields=["sunday_date"], name="attendance__sunday__24264c_idx"
                    ),
                    models.Index(
                        fields=["archdeaconry", "parish"],
                        name="attendance__archdea_33f682_idx",
                    ),
                ],
                "unique_together": {("congregation", "sunday_date")},
            },
        ),
    ]
